from __future__ import annotations

import re
from pathlib import Path

_FRONTMATTER_RE = re.compile(r"^---\n(.*?)\n---\n", re.DOTALL)


def _parse_frontmatter(text: str) -> dict[str, str]:
    match = _FRONTMATTER_RE.match(text)
    if not match:
        return {}
    meta: dict[str, str] = {}
    for line in match.group(1).splitlines():
        if ": " in line:
            key, _, value = line.partition(": ")
            meta[key.strip()] = value.strip()
    return meta


def _parse_themes(value: str) -> list[str]:
    """Parse a YAML inline list like [foo, bar] or a plain string."""
    value = value.strip()
    if value.startswith("[") and value.endswith("]"):
        return [t.strip() for t in value[1:-1].split(",") if t.strip()]
    return [value] if value else []


def regenerate_index(research_dir: Path) -> None:
    """Walk research/cards/, read frontmatters, write research/INDEX.md.

    Sorted by theme, then mentions_count desc, then discovered desc.
    """
    cards_dir = research_dir / "cards"
    index_path = research_dir / "INDEX.md"

    if not cards_dir.exists():
        index_path.write_text(
            "# Research Index\n\n_No cards yet. Run `/tech-watch` to populate._\n",
            encoding="utf-8",
        )
        return

    # Collect all cards
    by_theme: dict[str, list[dict]] = {}
    for card_path in sorted(cards_dir.rglob("*.md")):
        text = card_path.read_text(encoding="utf-8")
        meta = _parse_frontmatter(text)
        if not meta:
            continue

        themes = _parse_themes(meta.get("themes", ""))
        if not themes:
            themes = ["general"]

        for theme in themes:
            if theme not in by_theme:
                by_theme[theme] = []
            by_theme[theme].append(
                {
                    "path": card_path,
                    "title": meta.get("title", card_path.stem),
                    "source": meta.get("source", ""),
                    "source_url": meta.get("source_url", ""),
                    "pitch": meta.get("pitch", ""),
                    "mentions_count": int(meta.get("mentions_count", "1")),
                    "discovered": meta.get("discovered", ""),
                    "has_synthesis": meta.get("has_synthesis", "false").lower() == "true",
                }
            )

    # Build index content
    lines = [
        "# Research Index",
        "",
        "> Auto-generated by `/tech-watch`. Do not edit manually.",
        "> Last updated: see git log.",
        "",
    ]

    for theme in sorted(by_theme.keys()):
        cards = by_theme[theme]
        # Sort: mentions_count desc, discovered desc
        cards.sort(key=lambda c: (-c["mentions_count"], c["discovered"]), reverse=False)
        cards.sort(
            key=lambda c: (
                -c["mentions_count"],
                -(ord(c["discovered"][0]) if c["discovered"] else 0),
            )
        )

        lines.append(f"## {theme}")
        lines.append("")
        lines.append("| Title | Source | Mentions | Discovered | Synthesis |")
        lines.append("|-------|--------|----------|------------|-----------|")

        for card in cards:
            title_link = (
                f"[{card['title']}]({card['source_url']})" if card["source_url"] else card["title"]
            )
            synthesis = "✓" if card["has_synthesis"] else ""
            lines.append(
                f"| {title_link} | {card['source']} | {card['mentions_count']} "
                f"| {card['discovered']} | {synthesis} |"
            )
        lines.append("")

    index_path.write_text("\n".join(lines), encoding="utf-8")
