"""Generate multi-host stubs from the source-of-truth .claude/ + CLAUDE.md.

Usage:
    uv run python scripts/sync_hosts.py           # generate stubs
    uv run python scripts/sync_hosts.py --check   # verify stubs are up-to-date (exit 1 on drift)
"""

from __future__ import annotations

import argparse
import hashlib
import sys
from pathlib import Path

import yaml


def load_config(root: Path) -> dict:
    config_path = root / "sync-config.yaml"
    if not config_path.is_file():
        print("ERROR: sync-config.yaml not found", file=sys.stderr)
        sys.exit(1)
    return yaml.safe_load(config_path.read_text(encoding="utf-8"))


def config_exists(root: Path) -> bool:
    return (root / "sync-config.yaml").is_file()


def generate_import_stub(source_ref: str) -> str:
    return (
        f"<!-- Auto-generated by scripts/sync_hosts.py — do not edit manually -->\n"
        f"<!-- Source of truth: {source_ref} + .claude/ -->\n"
        f"\n"
        f"Read {source_ref} for all instructions, skills, and agent definitions.\n"
        f"All skills and agents defined there apply to this environment.\n"
    )


def content_hash(content: str) -> str:
    return hashlib.sha256(content.encode("utf-8")).hexdigest()[:12]


def sync(root: Path, check_only: bool = False) -> int:
    config = load_config(root)
    hosts = config.get("hosts", {})
    drifted: list[str] = []
    written: list[str] = []

    for name, host in hosts.items():
        if host.get("primary", False):
            continue

        fmt = host.get("format")
        target = root / host["target"]

        if fmt == "import-stub":
            source_ref = host.get("source_ref", "CLAUDE.md")
            expected = generate_import_stub(source_ref)

            if target.is_file():
                current = target.read_text(encoding="utf-8")
                if content_hash(current) == content_hash(expected):
                    continue

            if check_only:
                drifted.append(f"{name}: {target} is outdated")
            else:
                target.write_text(expected, encoding="utf-8")
                written.append(f"{name}: {target}")

        # Tier 2+ formats (cursorrules, markdown-flat) — not yet implemented.
        # When uncommented in sync-config.yaml, this block will handle them.

    if check_only:
        if drifted:
            print("sync --check FAILED:", file=sys.stderr)
            for d in drifted:
                print(f"  - {d}", file=sys.stderr)
            return 1
        print("sync --check OK (all stubs up-to-date)")
        return 0

    if written:
        print(f"sync OK — {len(written)} stub(s) written:")
        for w in written:
            print(f"  - {w}")
    else:
        print("sync OK — all stubs already up-to-date")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(
        prog="sync_hosts",
        description="Generate multi-host stubs from .claude/ + CLAUDE.md",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Verify stubs are up-to-date without writing (exit 1 on drift)",
    )
    args = parser.parse_args()

    root = Path(__file__).resolve().parent.parent
    # Single-host projects don't create sync-config.yaml. Skip gracefully
    # instead of blocking every commit that touches a skill or CLAUDE.md.
    if args.check and not config_exists(root):
        print("sync --check SKIP (no sync-config.yaml — single-host project)")
        return 0
    return sync(root, check_only=args.check)


if __name__ == "__main__":
    raise SystemExit(main())
